### ISSUE TITLE
Error during write-config: Unable to open file /etc/kea/kea-dhcp4.conf for writing

### ISSUE THREAD

**Issue by kifeo** [francoismdj/netbox-kea-dhcp#12]
Hi !

I've followed the install tutorial, but I end up with the following issue :

`2024-10-11 09:42:08,436 [ERROR] config push or write rejected: command "config-write" returns "Error during write-config: Unable to open file /etc/kea/kea-dhcp4.conf for writing"
`

the permissions for the file were kept as default :
-rw-r--r-- 1 _kea _kea 16960 Oct 10 14:03 kea-dhcp4.conf

BUT even with a chmod 646, I still have the same issue.

Thanks for the help!

**Comment by francoismdj** [comment]
Hello,
I checked on a fresh Ubuntu 24.04 container and got the same error until I disable Apparmor (and reboot).

My testing environnement:
- Ubuntu 24.04 LXC container
- ISC Kea DHCP4 (from apt install): 2.4.1

Test command:
```sh
echo '{ "command": "config-write", "arguments": { "filename": "/tmp/kea-test-write.json" } }' | socat UNIX:/run/kea/kea4-ctrl-socket -
```

Answer when Apparmor is running:
```json
{ "result": 1, "text": "Error during write-config: Unable to open file /tmp/kea-test-write.json for writing" }
```

Answer without Apparmor and after reboot:
```json
{ "arguments": { "filename": "/tmp/kea-test-write.json", "size": 3585 }, "result": 0, "text": "Configuration written to /tmp/kea-test-write.json successful" }
```

Hope it’s the same reason for you!

**Comment by kifeo** [comment]
Thanks indeed this worked, Thanks @francoismdj

**Comment by andusvan** [comment]
Please add this information to the readme. It took me a lot of time....
