### ISSUE TITLE
Feature-Request: Support for Plugin netbox-gateways

### ISSUE THREAD

**Issue by klenzel** [francoismdj/netbox-kea-dhcp#5]
Hello,

Thank you for your work on this plugin.
Would it be possible to implement support for the netbox-gateways plugin for the "option-data.routers" option?

Unfortunately, the routing information is not in Custom_fields but must be read from the API tree "plugins".

http://netbox/api/plugins/nb-gateways/gateway/

Thanks and Regards,
Daniel

**Comment by francoismdj** [comment]
Hi,
I’m sorry I will not be able to invest time to develop this feature but PR are welcomed :-)
François
