### ISSUE TITLE
ip-ranges dhcp status is not one of the valid choices

### ISSUE THREAD

**Issue by pvl1** [francoismdj/netbox-kea-dhcp#9]
[current location](https://github.com/francoismdj/netbox-kea-dhcp/blob/f53d9df9d44281d8e2768337a0f38a387420eef6/src/netboxkea/netbox.py#L8C21-L8C21) of issue: `ipaddress_filter={'status': 'dhcp'}` 
[netbox docs](https://demo.netbox.dev/static/docs/core-functionality/ipam/) explicitly state:
> Statuses are hard-coded in NetBox and can be one of the following:
> - Container - A summary of child prefixes
> - Active - Provisioned and in use
> - Reserved - Designated for future use
> - Deprecated - No longer in use

I'd suggest to change this to `roles` or, is there a plugin that creates extra status fields?

**Comment by francoismdj** [comment]
Hi pvl1,

The quoted text apply on prefixes. In the same page at [IP Address section](https://demo.netbox.dev/static/docs/core-functionality/ipam/#ip-addresses) we can found the (hardcoded) DHCP value.

Your comment may apply to IP Ranges as they do not have a hard-coded DHCP value whereas default iprange_filter rely on it. This default filter requires the addition of a custom status value, as documented [here](https://docs.netbox.dev/en/stable/models/ipam/iprange/#status).

**Comment by francoismdj** [comment]
Maybe link to custom IP range status should be inserted in README ?

**Comment by pvl1** [comment]
from netbox slack, it was suggested to either modify netbox config to include statuses (https://github.com/netbox-community/netbox/issues/8054) or to use tags
I think it'd be nice to include this in the readme
